<?php

namespace ContainerOeyVcnl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MIp9O3xService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mIp9O3x' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mIp9O3x'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'registry' => ['services', 'doctrine', 'getDoctrineService', false],
        ], [
            'registry' => '?',
        ]);
    }
}
