<?php

namespace ContainerOeyVcnl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTimeTrackingControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\FreelancerManager\TimeTrackingController' shared autowired service.
     *
     * @return \App\Controller\FreelancerManager\TimeTrackingController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/FreelancerManager/TimeTrackingController.php';

        $container->services['App\\Controller\\FreelancerManager\\TimeTrackingController'] = $instance = new \App\Controller\FreelancerManager\TimeTrackingController(($container->privates['App\\Service\\timeTrackingHelper'] ?? $container->load('getTimeTrackingHelperService')), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));

        $instance->setContainer(($container->privates['.service_locator.jUv.zyj'] ?? $container->load('get_ServiceLocator_JUv_ZyjService'))->withContext('App\\Controller\\FreelancerManager\\TimeTrackingController', $container));

        return $instance;
    }
}
