<?php

namespace Container6NXhb1V;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFlProjectsTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\FlProjectsType' shared autowired service.
     *
     * @return \App\Form\FlProjectsType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/FlProjectsType.php';

        return $container->privates['App\\Form\\FlProjectsType'] = new \App\Form\FlProjectsType();
    }
}
