<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class FlCustomer extends \App\Entity\FlCustomer implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'Active' => [parent::class, 'Active', null],
        "\0".parent::class."\0".'City' => [parent::class, 'City', null],
        "\0".parent::class."\0".'ContactEmail' => [parent::class, 'ContactEmail', null],
        "\0".parent::class."\0".'ContactName' => [parent::class, 'ContactName', null],
        "\0".parent::class."\0".'ContactPosition' => [parent::class, 'ContactPosition', null],
        "\0".parent::class."\0".'Country' => [parent::class, 'Country', null],
        "\0".parent::class."\0".'CreatedOn' => [parent::class, 'CreatedOn', null],
        "\0".parent::class."\0".'CustomerNumber' => [parent::class, 'CustomerNumber', null],
        "\0".parent::class."\0".'CustomerUrl' => [parent::class, 'CustomerUrl', null],
        "\0".parent::class."\0".'LastModifiedOn' => [parent::class, 'LastModifiedOn', null],
        "\0".parent::class."\0".'Name' => [parent::class, 'Name', null],
        "\0".parent::class."\0".'PhoneBusiness' => [parent::class, 'PhoneBusiness', null],
        "\0".parent::class."\0".'PhoneFax' => [parent::class, 'PhoneFax', null],
        "\0".parent::class."\0".'PhoneMobile' => [parent::class, 'PhoneMobile', null],
        "\0".parent::class."\0".'PhonePrivate' => [parent::class, 'PhonePrivate', null],
        "\0".parent::class."\0".'PostalCode' => [parent::class, 'PostalCode', null],
        "\0".parent::class."\0".'RefUser' => [parent::class, 'RefUser', null],
        "\0".parent::class."\0".'Street' => [parent::class, 'Street', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        'Active' => [parent::class, 'Active', null],
        'City' => [parent::class, 'City', null],
        'ContactEmail' => [parent::class, 'ContactEmail', null],
        'ContactName' => [parent::class, 'ContactName', null],
        'ContactPosition' => [parent::class, 'ContactPosition', null],
        'Country' => [parent::class, 'Country', null],
        'CreatedOn' => [parent::class, 'CreatedOn', null],
        'CustomerNumber' => [parent::class, 'CustomerNumber', null],
        'CustomerUrl' => [parent::class, 'CustomerUrl', null],
        'LastModifiedOn' => [parent::class, 'LastModifiedOn', null],
        'Name' => [parent::class, 'Name', null],
        'PhoneBusiness' => [parent::class, 'PhoneBusiness', null],
        'PhoneFax' => [parent::class, 'PhoneFax', null],
        'PhoneMobile' => [parent::class, 'PhoneMobile', null],
        'PhonePrivate' => [parent::class, 'PhonePrivate', null],
        'PostalCode' => [parent::class, 'PostalCode', null],
        'RefUser' => [parent::class, 'RefUser', null],
        'Street' => [parent::class, 'Street', null],
        'id' => [parent::class, 'id', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
