<?php

namespace Container6NXhb1V;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FH7pqtlService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fH7pqtl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fH7pqtl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'globalHelper' => ['privates', 'App\\Service\\globalHelper', 'getGlobalHelperService', true],
        ], [
            'globalHelper' => 'App\\Service\\globalHelper',
        ]);
    }
}
