<?php

namespace Container6NXhb1V;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAppConfigHelperService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\AppConfigHelper' shared autowired service.
     *
     * @return \App\Service\AppConfigHelper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/AppConfigHelper.php';

        return $container->privates['App\\Service\\AppConfigHelper'] = new \App\Service\AppConfigHelper(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));
    }
}
