<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2Sp65Mo\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2Sp65Mo/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2Sp65Mo.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2Sp65Mo\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2Sp65Mo\App_KernelDevDebugContainer([
    'container.build_hash' => '2Sp65Mo',
    'container.build_id' => 'dabf001d',
    'container.build_time' => 1746106373,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container2Sp65Mo');
