<?php

namespace ContainerOSL7NRY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SMgUl1wService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sMgUl1w' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sMgUl1w'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entriesRepository' => ['privates', 'App\\Repository\\FlProjectEntriesRepository', 'getFlProjectEntriesRepositoryService', true],
            'logger' => ['privates', 'monolog.logger', 'getMonolog_LoggerService', false],
        ], [
            'entriesRepository' => 'App\\Repository\\FlProjectEntriesRepository',
            'logger' => '?',
        ]);
    }
}
