<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXGA4S18\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXGA4S18/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXGA4S18.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXGA4S18\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXGA4S18\App_KernelDevDebugContainer([
    'container.build_hash' => 'XGA4S18',
    'container.build_id' => '9b9c34af',
    'container.build_time' => 1746107625,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXGA4S18');
