<?php

namespace Container0YLzTj4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YGwDiRxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YGwDiRx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YGwDiRx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'customerRepository' => ['privates', 'App\\Repository\\FlCustomerRepository', 'getFlCustomerRepositoryService', true],
            'flProjectsRepository' => ['privates', 'App\\Repository\\FlProjectsRepository', 'getFlProjectsRepositoryService', true],
        ], [
            'customerRepository' => 'App\\Repository\\FlCustomerRepository',
            'flProjectsRepository' => 'App\\Repository\\FlProjectsRepository',
        ]);
    }
}
