<?php

namespace Container0YLzTj4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFlProjectsRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\FlProjectsRepository' shared autowired service.
     *
     * @return \App\Repository\FlProjectsRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/persistence/src/Persistence/ObjectRepository.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/collections/src/Selectable.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/orm/src/EntityRepository.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/Repository/ServiceEntityRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/Repository/LazyServiceEntityRepository.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/Repository/ServiceEntityRepository.php';
        include_once \dirname(__DIR__, 4).'/src/Repository/FlProjectsRepository.php';

        $a = ($container->privates['App\\Twig\\AppRuntime'] ?? $container->load('getAppRuntimeService'));

        if (isset($container->privates['App\\Repository\\FlProjectsRepository'])) {
            return $container->privates['App\\Repository\\FlProjectsRepository'];
        }

        return $container->privates['App\\Repository\\FlProjectsRepository'] = new \App\Repository\FlProjectsRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)), $a);
    }
}
