<?php

namespace Container0YLzTj4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImportFilterControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\KontoManager\ImportFilterController' shared autowired service.
     *
     * @return \App\Controller\KontoManager\ImportFilterController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/KontoManager/ImportFilterController.php';

        $container->services['App\\Controller\\KontoManager\\ImportFilterController'] = $instance = new \App\Controller\KontoManager\ImportFilterController(($container->services['doctrine'] ?? self::getDoctrineService($container)), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));

        $instance->setContainer(($container->privates['.service_locator.jUv.zyj'] ?? $container->load('get_ServiceLocator_JUv_ZyjService'))->withContext('App\\Controller\\KontoManager\\ImportFilterController', $container));

        return $instance;
    }
}
