<?php

namespace Container0SsY5Us;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JwLmlhfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JwLmlhf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JwLmlhf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'importFilter' => ['privates', 'App\\Service\\kmImportFilter', 'getKmImportFilterService', true],
            'logger' => ['privates', 'monolog.logger', 'getMonolog_LoggerService', false],
            'registry' => ['services', 'doctrine', 'getDoctrineService', false],
        ], [
            'importFilter' => 'App\\Service\\kmImportFilter',
            'logger' => '?',
            'registry' => '?',
        ]);
    }
}
