<?php

namespace Container0SsY5Us;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DB2Lhi6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DB2Lhi6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DB2Lhi6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'registry' => ['services', 'doctrine', 'getDoctrineService', false],
            'tcpdf' => ['privates', 'App\\Service\\tcpdf_helper', 'getTcpdfHelperService', true],
        ], [
            'registry' => '?',
            'tcpdf' => 'App\\Service\\tcpdf_helper',
        ]);
    }
}
