<?php

namespace Container0SsY5Us;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFlProjectsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.sXpIIRH.App\Entity\FlProjects' shared service.
     *
     * @return \App\Entity\FlProjects
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.sXpIIRH": it needs an instance of "App\\Entity\\FlProjects" but this type has been excluded in "config/services.yaml".');
    }
}
