<?php

namespace Container0SsY5Us;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGlobalHelperService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\globalHelper' shared autowired service.
     *
     * @return \App\Service\globalHelper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/globalHelper.php';

        return $container->privates['App\\Service\\globalHelper'] = new \App\Service\globalHelper();
    }
}
