<?php

namespace Container0SsY5Us;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPDFControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\FreelancerManager\PDFController' shared autowired service.
     *
     * @return \App\Controller\FreelancerManager\PDFController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/FreelancerManager/PDFController.php';

        $container->services['App\\Controller\\FreelancerManager\\PDFController'] = $instance = new \App\Controller\FreelancerManager\PDFController(($container->privates['App\\Service\\ReportingHelper'] ?? $container->load('getReportingHelperService')), ($container->privates['App\\Service\\tcpdf_helper'] ?? $container->load('getTcpdfHelperService')), ($container->privates['App\\Repository\\FlConfigurationRepository'] ?? $container->load('getFlConfigurationRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.jUv.zyj'] ?? $container->load('get_ServiceLocator_JUv_ZyjService'))->withContext('App\\Controller\\FreelancerManager\\PDFController', $container));

        return $instance;
    }
}
