<?php

namespace Container2Sp65Mo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getKmImportFilterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\kmImportFilter' shared autowired service.
     *
     * @return \App\Service\kmImportFilter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/kmImportFilter.php';

        return $container->privates['App\\Service\\kmImportFilter'] = new \App\Service\kmImportFilter(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
