<?php

namespace Container2Sp65Mo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReportingHelperService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\ReportingHelper' shared autowired service.
     *
     * @return \App\Service\ReportingHelper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/ReportingHelper.php';

        return $container->privates['App\\Service\\ReportingHelper'] = new \App\Service\ReportingHelper(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));
    }
}
