<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.js',
                '/build/app.js',
            ],
        ],
        'home' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_swiper_swiper-bundle_css-node_modules_swiper_swiper-bundle_mjs.js',
                '/build/home.js',
            ],
            'css' => [
                '/build/vendors-node_modules_swiper_swiper-bundle_css-node_modules_swiper_swiper-bundle_mjs.css',
                '/build/home.css',
            ],
        ],
        'about' => [
            'js' => [
                '/build/runtime.js',
                '/build/about.js',
            ],
            'css' => [
                '/build/about.css',
            ],
        ],
        'services' => [
            'js' => [
                '/build/runtime.js',
                '/build/services.js',
            ],
            'css' => [
                '/build/services.css',
            ],
        ],
        'blog' => [
            'js' => [
                '/build/runtime.js',
                '/build/blog.js',
            ],
            'css' => [
                '/build/blog.css',
            ],
        ],
        'formations' => [
            'js' => [
                '/build/runtime.js',
                '/build/formations.js',
            ],
            'css' => [
                '/build/formations.css',
            ],
        ],
        'contact' => [
            'js' => [
                '/build/runtime.js',
                '/build/contact.js',
            ],
            'css' => [
                '/build/contact.css',
            ],
        ],
        'training' => [
            'js' => [
                '/build/runtime.js',
                '/build/training.js',
            ],
            'css' => [
                '/build/training.css',
            ],
        ],
    ],
],

]];
