<?php

namespace ContainerXGA4S18;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MFTyQUCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MFTyQUC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MFTyQUC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'entriesRepository' => ['privates', 'App\\Repository\\FlProjectEntriesRepository', 'getFlProjectEntriesRepositoryService', true],
            'projectsRepository' => ['privates', 'App\\Repository\\FlProjectsRepository', 'getFlProjectsRepositoryService', true],
        ], [
            'em' => '?',
            'entriesRepository' => 'App\\Repository\\FlProjectEntriesRepository',
            'projectsRepository' => 'App\\Repository\\FlProjectsRepository',
        ]);
    }
}
