<?php

namespace ContainerXGA4S18;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOverviewControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\KontoManager\OverviewController' shared autowired service.
     *
     * @return \App\Controller\KontoManager\OverviewController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/KontoManager/OverviewController.php';

        $container->services['App\\Controller\\KontoManager\\OverviewController'] = $instance = new \App\Controller\KontoManager\OverviewController();

        $instance->setContainer(($container->privates['.service_locator.jUv.zyj'] ?? $container->load('get_ServiceLocator_JUv_ZyjService'))->withContext('App\\Controller\\KontoManager\\OverviewController', $container));

        return $instance;
    }
}
