<?php

namespace ContainerXGA4S18;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReportingControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\FreelancerManager\ReportingController' shared autowired service.
     *
     * @return \App\Controller\FreelancerManager\ReportingController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/FreelancerManager/ReportingController.php';

        $container->services['App\\Controller\\FreelancerManager\\ReportingController'] = $instance = new \App\Controller\FreelancerManager\ReportingController(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Service\\ReportingHelper'] ?? $container->load('getReportingHelperService')));

        $instance->setContainer(($container->privates['.service_locator.jUv.zyj'] ?? $container->load('get_ServiceLocator_JUv_ZyjService'))->withContext('App\\Controller\\FreelancerManager\\ReportingController', $container));

        return $instance;
    }
}
