<?php

namespace Container2Sp65Mo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTcpdfHelperService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\tcpdf_helper' shared autowired service.
     *
     * @return \App\Service\tcpdf_helper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/tcpdf_helper.php';

        return $container->privates['App\\Service\\tcpdf_helper'] = new \App\Service\tcpdf_helper(($container->privates['parameter_bag'] ??= new \Symfony\Component\DependencyInjection\ParameterBag\ContainerBag($container)));
    }
}
