<?php

namespace Container9QWmByo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZbuTZavService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZbuTZav' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZbuTZav'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'customerRepository' => ['privates', 'App\\Repository\\FlCustomerRepository', 'getFlCustomerRepositoryService', true],
            'flInvoicesRepository' => ['privates', 'App\\Repository\\FlInvoicesRepository', 'getFlInvoicesRepositoryService', true],
        ], [
            'customerRepository' => 'App\\Repository\\FlCustomerRepository',
            'flInvoicesRepository' => 'App\\Repository\\FlInvoicesRepository',
        ]);
    }
}
