<?php

namespace Container9QWmByo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GZhqEaCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gZhqEaC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gZhqEaC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'appConfigHelper' => ['privates', 'App\\Service\\AppConfigHelper', 'getAppConfigHelperService', true],
            'registry' => ['services', 'doctrine', 'getDoctrineService', false],
        ], [
            'appConfigHelper' => 'App\\Service\\AppConfigHelper',
            'registry' => '?',
        ]);
    }
}
