<?php

namespace Container5zEZy8g;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6QkR5sPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6QkR5sP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6QkR5sP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'entriesRepository' => ['privates', 'App\\Repository\\FlProjectEntriesRepository', 'getFlProjectEntriesRepositoryService', true],
        ], [
            'em' => '?',
            'entriesRepository' => 'App\\Repository\\FlProjectEntriesRepository',
        ]);
    }
}
