<?php

namespace Container5zEZy8g;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NxXAkgqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nxXAkgq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nxXAkgq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'customersRepository' => ['privates', 'App\\Repository\\FlCustomerRepository', 'getFlCustomerRepositoryService', true],
            'invoicesRepository' => ['privates', 'App\\Repository\\FlInvoicesRepository', 'getFlInvoicesRepositoryService', true],
            'projectsRepository' => ['privates', 'App\\Repository\\FlProjectsRepository', 'getFlProjectsRepositoryService', true],
        ], [
            'customersRepository' => 'App\\Repository\\FlCustomerRepository',
            'invoicesRepository' => 'App\\Repository\\FlInvoicesRepository',
            'projectsRepository' => 'App\\Repository\\FlProjectsRepository',
        ]);
    }
}
