<?php

namespace Container5zEZy8g;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6zv461Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._6zv461' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._6zv461'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entriesRepository' => ['privates', 'App\\Repository\\FlProjectEntriesRepository', 'getFlProjectEntriesRepositoryService', true],
            'projectsRepository' => ['privates', 'App\\Repository\\FlProjectsRepository', 'getFlProjectsRepositoryService', true],
        ], [
            'entriesRepository' => 'App\\Repository\\FlProjectEntriesRepository',
            'projectsRepository' => 'App\\Repository\\FlProjectsRepository',
        ]);
    }
}
