<?php

namespace Container5zEZy8g;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProjectsControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\FreelancerManager\ProjectsController' shared autowired service.
     *
     * @return \App\Controller\FreelancerManager\ProjectsController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/FreelancerManager/ProjectsController.php';

        $container->services['App\\Controller\\FreelancerManager\\ProjectsController'] = $instance = new \App\Controller\FreelancerManager\ProjectsController(($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)), ($container->privates['App\\Service\\AppConfigHelper'] ?? $container->load('getAppConfigHelperService')));

        $instance->setContainer(($container->privates['.service_locator.jUv.zyj'] ?? $container->load('get_ServiceLocator_JUv_ZyjService'))->withContext('App\\Controller\\FreelancerManager\\ProjectsController', $container));

        return $instance;
    }
}
