<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6NXhb1V\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6NXhb1V/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6NXhb1V.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6NXhb1V\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6NXhb1V\App_KernelDevDebugContainer([
    'container.build_hash' => '6NXhb1V',
    'container.build_id' => '947a3e1f',
    'container.build_time' => 1746137638,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container6NXhb1V');
